### ISSUE TITLE
Use Meson as build system

### ISSUE THREAD

**Issue by kou** [pgroonga/pgroonga#490]
### What is your problem?

Because PostgreSQL will use Meson as the default build system.

**Comment by otegami** [comment]
I will want to start this issue step by step.
- https://www.youtube.com/watch?v=SAK5RAHwzVQ

**Comment by otegami** [comment]
## TODO

- [ ] handle vendored xxHash
  - https://github.com/pgroonga/pgroonga/pull/750#discussion_r2165171125
- [ ] add test steps
  - https://github.com/pgroonga/pgroonga/pull/750#discussion_r2165188152 
- [ ] add scripts which are used in Make-based build
- [ ] support multi platforms
